### ISSUE TITLE
Serialkey management 

### ISSUE THREAD

**Issue by zooeyjapan** [Masuzu/GBFCombatSniffer#8]
Hi,
Not exactly an issue,  more a question;
 
I've been testing with GCP with a gpu backed instance  and i want to alternate to one without to save on costs for tasks where speed is less of a concern. However when i use an image or snapshot i created before, the serial key of the new instance  with and without gpu seem to be always different, hence its locked to in this case my gpu instance.

In my account management, any serial key change applies to all products, hence I can't use ie combatsniffer on the gpu backed instance and the zooey bot on the non gpu backed instance, or switch them easily (except once every 4 days which limits the tests). 
Is there a way to simplify this, or a way to keep the serial key generation unique across gcp instance with/without gpu, other than creating an additional accounts with extra keys?
Thanks you.

**Comment by zooeyjapan** [comment]
One additional question; 
Quick joining of raids -> VM removed it due to cygames supposedly building detection on it. Does the combat sniffer not trigger this, even though the output on screen appears it to be the same as how it was with quickjoin and VM?

**Comment by zooeyjapan** [comment]
I feel this github is probably not the right place for these kinds of questions, but there is little resource available on this. If you know of a better location please let me know. 

With your YT video, there is a level of smoothness i can't yet reproduce. reloading is instant obviously, but any graphical animation still slows down tremendously, even though chrome has hardware acceleration properly configured. Did you go with the standard grid settings or switch to quadro, use standard RDP or try some remotefx settings, or maybe teamviewer or parsec? Maybe im simply running into limitaitons of EU <> tokyo GCP as the throughput isn't amazing for any graphical animations.

**Comment by Masuzu** [comment]
I also play mainly from Europe. There is a significant drop in FPS due to the round robin trip between your machine and the node in Tokyo, at least using Windows Remote desktop. Other remote desktop solutions might prove more effective (Chrome has its own Remote desktop tool as well) than the one offered by Windows, but I have not tried those, as I found my "sweet spot" in terms of practicability:

Personally, the FPS drop is the reason why I refresh after any action (whether it is casting an ability, using a consumable item or a summon) with the back -> forward method which, granted, in some cases, results in the game being unresponsive and forces you to reload the page with F5. For anything which requires MVP I use machines with GPUs (Japan datacenters are one of the only few offered by Google with the latest Nvidia T4 GPUs). The bottleneck is still the quality of your connection: depending on the remote desktop solution you use, even if you can render 1000 frames per second and that it takes 1 second to render it back on your remote desktop window, it is going to be quite a painful experience... 
Ability and attack shortcuts permits casting skills without waiting for the animation loading lockout, so the constant reloading mitigates the terrible FPS. You can see it as switching between Powerpoint slides quickly enough to skip all the transition animations between them. It may not feel natural but there is always a balance between what you want to achieve and the extents of how far you have to go, echoing to your mentioning the quick raid joining feature.

**Comment by zooeyjapan** [comment]
Hi Masuzu, 

Thank you for your great feedback.
